### ISSUE TITLE
Is running on Windows 10 WSL supported?

### ISSUE THREAD

**Issue by alzadude** [Deep-Symmetry/dysentery#18]
**Description**
I'm trying to run in WSL on Windows 10 since that's where my Java/Clojure tooling is installed, but I when I run `(dysentery.view/find-devices)` from a REPL I get `No DJ Link devices found; giving up.`

I already checked that it's not a network error (Rekordbox presents the link button bottom left when opened, and my CDJ's are detected etc).

**Steps to Reproduce**
1. Start WSL bash shell
2. Git clone project
3. `cd dysentery` 
4. `lein repl`
5. `(view/find-devices)`
```
Looking for DJ Link devices...
```
4. Get error message
```
No DJ Link devices found; giving up.
nil
```

**Expected Behavior**
DJ link devices are found

**Desktop**
 - OS: Windows 10, WSL, Debian 10 Buster
 - Java Version: `openjdk version "1.8.0_242-ea"`
 - Project Version: Git master `83bdeb2ffd375993252b784dfc7971304f6412e5`

**Additional context**
2x CDJ-2000NXS2
1x DJM-900NXS2
Connected to Windows 10 laptop via ethernet switch.

**Comment by brunchboy** [comment]
I’m sorry, I have no idea what WSL is, and don’t use Windows. But this is an experimental project, so nothing is “supported”, it’s just a platform for exploring. I’d welcome any discoveries you can share about this.

**Comment by brunchboy** [comment]
If you can find any ways to make this work, a pull request would be welcome, and if you prove that it cannot work, we can update the read me.

**Comment by brunchboy** [comment]
One thing that did catch my eye, why are you using Java 8 rather than 13 (or even 11)?

**Comment by alzadude** [comment]
Hey!

WSL is the Windows Subsystem for Linux, it allows Linux distributions (and therefore Linux pre-compiled apps/binaries) to run on Windows without modification or requiring a virtual machine: https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux

I'm running an older version of the OpenJDK at the moment because that's what I need for a couple other (unrelated) projects I'm working on. I could try with 11 though, as I've got that installed as well.

When I say "supported" I guess I meant "a combination of OS, Java version, Clojure version, network setup and hardware, for which the application has been observed to work successfully", if that makes sense.

If I know that, then I can try and make my environment as close to that as possible whilst making these initial attempts. The Mac part of that would be hard for me though, as I don't have one...

Btw is there a way to turn logging on when I try this?

**Comment by brunchboy** [comment]
Ah, thanks for the clarification, I had heard of that but didn’t make the connection from the acronym. It does sound like a great direction for Windows to be evolving.

It would not surprise me if there were some problematic interaction between WSL and Java and the networking stack, though, I think your instinct is right. The reason I asked about Java versions was that Beat Link Trigger has some issues with the GUI in Java 8 on windows, but I don’t think it will be a problem for dysentery and the kind of testing you are doing.

I don’t remember having any logging in dysentery, because I threw it together as a way to experiment with protocol details in the REPL before writing them up in the big LaTeX document and then implementing them in Java as Beat Link (which does have logging, because I expected actual projects to use it). Let me take a quick look. Ok, I did pull in timbre, at least, so there may be some. But I am having to trace through the source code, it’s been years since I worked on this, sorry. It looks like there isn’t any logging code in the places that are watching for DJ Link devices, but you could add some:
https://blt-guide.deepsymmetry.org/beat-link-trigger/link#passive-sync

The code is intensely simple, though: it simply opens a socket on the broadcast port that the devices send their announcement packets to, and then for any such packets received, makes a note of the existence of that device. Since you are not seeing any devices, it means the packets are not getting to that socket under WSL for whatever reason.

**Comment by brunchboy** [comment]
Sorry, the first version of the previous comment had an incorrect link in it. It’s been fixed. You can find the theory behind what dysentery is doing to detect devices in Section 2 of the protocol analysis document, https://deepsymmetry.org/dysentery/Analysis.pdf

It is watching for CDJ or mixer status packets being sent to the network broadcast address on port 50000.

**Comment by alzadude** [comment]
Thanks for the info!

I just tried netcat in WSL to narrow it down:
```
sudo nc -ulp 50000
Can't grab 0.0.0.0:50000 with bind : Permission denied
```
And that was with sudo! So yes perhaps there's a networking aspect here that I don't understand yet.. 😕

**Comment by brunchboy** [comment]
Interesting. For what it’s worth people use Beat Link Trigger in Windows (outside of WSL) successfully all the time, so hopefully you’ll have more luck there.

Out of curiosity, why are you diving into this at the level of dysentery, rather than one of the more polished and full-featured projects like Beat Link Trigger or even the Beat Link library it uses? Do you have ideas about ways to support more of the DJ Link protocol?

**Comment by brunchboy** [comment]
…and a thought prompted from another issue discussion I just saw: if you have rekordbox running on the same machine, you are going to see issues like this, because it has opened port 50000 and no other process will be able to.

**Comment by alzadude** [comment]
Aha I just closed Rekordbox 😄

So the netstat command is working now, but I'm not seeing any output.. I don't know what to expect? I suppose this could still be some as-yet-unknown networking issue.

I was looking at this lib because I was thinking of implementing a server with an api against which clients could connect and run queries that return JSON data, where the clients could be: 

- a single-page webapp which gets the data and displays current playing track etc
- an app which gets the data and makes an image with current playing track etc

These are for use with OBS studio for streaming. However, after thinking of the idea, I Googled around some more and found [prolink-tools](https://github.com/EvanPurkhiser/prolink-tools/) overlay, and so it looks like I've been beaten to it!

However the problem with Rekordbox taking the socket means that tracks can't be played in link export mode (unless you run the prolink-tools server on another separate host), so it's of limited use to me - I'd want to use link export mode a lot of the time.

**Comment by brunchboy** [comment]
Dysentery isn’t a library, though. Beat Link is the library. It has a _ton_ of features that would make what you are talking about easy. (And if you want to be in Clojure, then Beat Link Trigger provides a friendly wrapper around that and all kinds of built in automation for integration with other things like Ableton Link and Open Sound Control.) People use that with OBS studio. And yes, prolink-tools are cool! This is a pretty tight-knit community of people figuring out how to do cool things with the protocol. 😄 

But unfortunately because of the short-sighted design of that protocol, yes, you are stuck, unless you want to invest a few bucks into a Raspberry Pi to run alongside Rekordbox.

**Comment by alzadude** [comment]
Ah thanks I didn't realise this, I initially thought Beat Link was a bit higher level than just an API, since the readme mentions it has a GUI etc. Plus the Dysentery readme mentioned the Clojure REPL explicitly so I thought I'd start there, as initially I just wanted to check if the network side of things worked in a WSL environment (and as I then discovered, this is where I have an issue aha).

So until I get that working, I wasn't going to worry about progressing further.

I also tried Prolink Tools (both in WSL and in Windows directly, since the project provides Linux and Windows binaries), but I hit an issue: https://github.com/EvanPurkhiser/prolink-tools/issues/6

So that issue at least, is unrelated to WSL it seems, because I get the same result when using Windows directly.

I'm not sure how widely tested/used Prolink Tools is on Windows, so I'm not sure whether I should expect it to work. I did manage to see the DJ Link packets on UDP 50000 with Wireshark CLI on Windows, but not with the Wireshark CLI in WSL. Although when I Googled about that briefly, it seems WSL networking is limited when it comes to packet sniffing, which makes the WSL issue hard to investigate, although for me it doesn't explain why Prolink Tools is not working (on WSL), since presumably the app is just trying to open a normal server socket on port 50000, rather than doing anything fancy like packet sniffing (or am I wrong?)

I'd like to leave this issue open though, just to investigate and understand why the network side of things is not working for WSL.

If I get some time, I'll separately install a Java/Clojure stack directly on Windows, that will at least establish whether the issue I'm seeing is specifically around WSL networking, or something else. I would also like to try WSL2, which is a full Linux kernel for Windows (!), but this is not officially released yet.

Although I have to say I'm reluctant to do that, since I find WSL so much easier for setting up dev tools compared to Windows, even with Chocolatey or Scoop etc. But it looks like in this instance, I have no choice 🤷‍♂️

Anyway if I get everything working from a networking perspective, I expect the Prolink Tools Overlay will be sufficient for my needs in the near term. However, it could be an interesting Clojure project to make a websockets server which could be a drop-in replacement for the Prolink Tools server, so that the Overlay works with it (or any other clients people may write for that matter). Almost like an emerging (Swagger/AsyncAPI?) web API for DJ Link apps, to break out from the lower level protocol and the various per-language API libraries/bindings etc.

**Comment by brunchboy** [comment]
Sorry about the confusion: there are separate projects of mine with similar names: _Beat Link_ is a Java library implementing a nice API over the DJ Link protocol (and also embeds some other projects like _Crate Digger_ for reading exported rekordbox media and _Electro_ for managing musical timelines when taking over as tempo master); _Beat Link Trigger_ is a Clojure GUI application for building integrations on top of Beat Link, as well as other libraries like _Beat Carabiner_ which enables it to synchronize with an Ableton Link session. There has been a lot of productive development over the years!

And I do toy with the idea of separating the Beat Link Trigger GUI from the underlying engine, offering a network service to allow other applications to manage that. I would use GraphQL rather than something like Swagger though. And the development of new features keep taking priority over that major refactoring effort. For now, you can achieve something similar (albeit more limited) using Open Beat Control, which offers an Open Sound Control API for remote management of Beat Link.

**Comment by brunchboy** [comment]
Oh, I forgot to respond to this:

> Although when I Googled about that briefly, it seems WSL networking is limited when it comes to packet sniffing, which makes the WSL issue hard to investigate, although for me it doesn't explain why Prolink Tools is not working (on WSL), since presumably the app is just trying to open a normal server socket on port 50000, rather than doing anything fancy like packet sniffing (or am I wrong?)

The difference might be that the packets being sent to port 50000 are broadcast packets, not directly addressed to any host, and maybe they have problems crossing over to WSL?

In any case, this does not appear to be an issue with dysentery, so I would like to close it.
