### ISSUE TITLE
Description of Bytes 24-27 in figure 9 is misleading

### ISSUE THREAD

**Issue by JalaJalera** [Deep-Symmetry/dysentery#19]
Hey, 
first of all thanks for your great analysis!

By examining the packets on XDJ 700s, I found out that the bytes 24-27 in the beat packets indicate when the next beat would arrive if the pitch was at zero percent. Is this the same with other CDJs/XDJs?
In the document it is written that "nextBeat at bytes 24–27 is the number of milliseconds in which the very next beat will arrive" (see page 9).

Greetings,
Julian

**Comment by brunchboy** [comment]
Ah, interesting! I haven’t tried seeing if pitch has an impact on that. I’ll do some tests with my CDJs and verify your finding, and update the document accordingly. Thanks very much for the report.

**Comment by brunchboy** [comment]
Indeed you are right, on my CDJ-2000 nexus players as well, the upcoming beat timings ignore the pitch adjustment. I have updated the LaTeX source to reflect this, thanks again.

It took me much longer than I would like to update the document, because it turns out that the `tabu` package I use for my tables is no longer maintained, and it has stopped working with current versions of TeX. So I had to downgrade to last year’s TeX release when I finally figured that out. I would really like to migrate these documents to Asciidoc like the rest of my documentation, but there is not yet a way to draw the kind of packet diagrams I need.

But also while I was doing this experiment and had dysentery running, I made some new discoveries about bytes `37` and `46`–`47` in the player status packets, so I am updating that section as well.
