### ISSUE TITLE
A warning appears with the new CDJ-3000

### ISSUE THREAD

**Issue by SamuChR** [Deep-Symmetry/dysentery#27]
**Describe the bug**
With the new CDJ-3000, when the application is launched, a warning appears.

**To Reproduce**
Run Dysentery as an executable jar.
`> java -jar dysentery.jar`

**Console**

```
D:\Users\Mini PC\Desktop\CDJ-3000>java -jar dysentery.jar
Looking for DJ Link devices...
Found:
   CDJ-3000 1 /169.254.6.99
   CDJ-3000 2 /169.254.6.119

To communicate create a virtual CDJ with address /169.254.2.30,
MAC address 00:e1:5c:68:33:07, and use broadcast address /169.254.255.255

Close any Player window to exit.
20-09-26 15:02:30 DESKTOP-MINI-PC WARN [dysentery.view:64] - Expecting packet of length #{284 208 292 212} but it has length 512
20-09-26 15:02:31 DESKTOP-MINI-PC WARN [dysentery.view:64] - Expecting packet of length #{284 208 292 212} but it has length 512
20-09-26 15:02:31 DESKTOP-MINI-PC WARN [dysentery.view:64] - Expecting packet of length #{284 208 292 212} but it has length 512
```

**Additional context**
Capturing udp packets with wireshark, when dysentery is launched, the packets on port 5001 are 102 bytes long and those on port 5002 are 292 bytes long.

**Comment by brunchboy** [comment]
Thanks, since it will probably be a long time before I get access to any CDJ-3000s, and since you seem to be able to use Wireshark, could you capture a session of the CDJ powering up and joining the network, and share it? For now I will probably just remove the warning since we will know about the larger packet sizes, but if you could identify any of the new information found in the longer packets and share that, perhaps as pull requests to update the packet analysis, but even just as detailed descriptions, that would be wonderful.
